security:
  oauth2:
    client:
      clientId: "@!661D.077A.F9DC.CB15!0001!22D5.6DE1!0008!AD75.0F41.992D.E96E"
      #clientId: QCE5ODhFLkE5QzMuOEE2OC5BRTExITAwMDEhQzU1OS4yOTgyITAwMDghOTkwMi44NzIxLkI1NDUuMTY0Ng==
      #clientSecret: Y2xpZW50U2VjcmV0
      clientSecret: clientSecret
      accessTokenUri: https://sso002.svugoogle.com/oxauth/seam/resource/restv1/oxauth/token
      userAuthorizationUri: https://sso002.svugoogle.com/oxauth/seam/resource/restv1/oxauth/authorize
      #tokenName: oauth_token
      #tokenName: javax.faces.ClientToken
      authenticationScheme: form
      clientAuthenticationScheme: form
      scope: openid
      #registered-redirect-uri: 
      #  http://localhost:8080
      #  https://sso002.svugoogle.com/oxauth/login
    resource:
      userInfoUri: https://sso002.svugoogle.com/oxauth/seam/resource/restv1/oxauth/authorize
logging:
  level:
    root: DEBUG