security:
  oauth2:
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: https://sso.svugoogle.com/oxauth/seam/resource/restv1/oxauth/token
      userAuthorizationUri: https://sso.svugoogle.com/oxauth/seam/resource/restv1/oxauth/authorize
      tokenName: oauth_token
      authenticationScheme: form
      clientAuthenticationScheme: form
      scope: openid
    resource:
      userInfoUri: https://sso.svugoogle.com/oxauth/seam/resource/restv1/oxauth/authorize